#ifndef ATTENDANCEACCESSOR_GLOBAL_H
#define ATTENDANCEACCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ATTENDANCEACCESSOR_LIBRARY)
#  define ATTENDANCEACCESSOR_EXPORT Q_DECL_EXPORT
#else
#  define ATTENDANCEACCESSOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ATTENDANCEACCESSOR_GLOBAL_H
